version: "3.8"

secrets:
  mautrix-facebook-registration.yml:
    file: ./mautrix-facebook/registration.yaml
  from-scratch-registration.yaml:
    file: ./packages/from-scratch/registration.yaml

volumes:
  pg-data:

services:
  synapse:
    depends_on:
      - postgres
    container_name: synapse
    image: matrixdotorg/synapse:latest
    secrets:
      - from-scratch-registration.yaml 
      - mautrix-facebook-registration.yml
    volumes:
      - ./synapse-data:/data
    ports:
      - 8008:8008
    # logging:
    #   driver: none
  # mautrix-facebook:
  #   container_name: mautrix-facebook
  #   depends_on:
  #     - synapse
  #   image: dock.mau.dev/mautrix/facebook:latest
  #   restart: unless-stopped
  #   volumes:
  #   - ./mautrix-facebook:/data
  from-scratch:
    container_name: from-scratch
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    command: yarn workspace from-scratch dev
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    # ports:
    #   - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
  adminer:
    image: adminer
    restart: unless-stopped 
    ports:
      - 8080:8080